### ISSUE TITLE
Application_Name with a space

### ISSUE THREAD

**Issue by haichenw** [jobee/pipeline-to-elasticbeanstalk#1]
Is it possible to use an application_name variable with a space? The elastic beanstalk environment im using has a space in it and we'd prefer not to change it. Thanks

I've tried quotation marks and removing the space but neither seems to work

PS Thank you for making this. It's really useful and simple. A lot of the other tutorials are way too complex.

**Comment by jobee** [comment]
Hey @haichenw 
using single quotes in https://github.com/jobee/pipeline-to-elasticbeanstalk/blob/master/eb-init.sh#L35-L36 like...

```yaml
global:
  application_name: '%s'
```
probably works.

Unfortunately I can't test this right now, since my client moved away from AWS :(
But I'm happy to accept and merge a PR if you want to fix and test this.

**Comment by haichenw** [comment]
Thanks Joachim. I ended up just moving to a new app name as i find things like this end up haunting me for little benefit. Appreciate the help :)

**Comment by jobee** [comment]
Ok, thats probably easier :) will close this issue then
